### ISSUE TITLE
Error on Tab Mail

### ISSUE THREAD

**Issue by Jayuda** [sb-minimal/docker-ubuntu-open-exchange#1]
Hello Guys,

I have error on tab mail. Error messages : 
`Could not get a default folder for this application. Application may not work as expected until this problem is solved.`

alse error : 
`Error while communicating with the sieve server localhost at port 2000 for user xxx in context 1`

Any sugestions ?
Thanks

**Comment by sb-minimal** [comment]
For me, I only got this error once on the first login and everything works fine afterwards. 
As far as i can tell, that is because the users mailfolder is missing some subfolders like "trash", "drafts", ... at first. (but seems as if OX is creating them).

Regarding the second error: Yes, there is no sieve server running on port 2000, as OX does not bundle its own mailserver, but is meant to be used with your own existing infrastructure.
Some features like autoresponder/holiday notification make use of a sieve server and will not work without it.

For production use, you should configure OX to use your existing mailserver and make sure all default folders like "trash", "drafts", ... are setup before the users log into OX.
Also, for autoresponder to work, you need to have a sieve server running and point OX to it (see the mailfilter.properties configuration file)
